### ISSUE TITLE
No acquisition run available: failed pre-condition error 

### ISSUE THREAD

**Issue by ChloeDG** [skovaka/UNCALLED#15]
Awesome tool, congrats on setting this up!

I am trying to run Uncalled realtime and I am getting some errors.
I created an environment and installed UNCALLED and read_until_api from git in it.  

I set up the build using: 
```
python3 setup.py build_ext --library-dirs /home/hh/UNCALLED/submods/hdf5/lib/ --include-dirs /home/hh/UNCALLED/submods/hdf5/include/
sudo python3 setup.py install
```
I was able to index my fasta and perform mapping of fast5s sucessfully, but when I attempt to run realtime using: 

```
uncalled realtime /home/hh/Documents/refs/HBV_GA/HBV_GA_2.fasta --port 8000 -t 16 --enrich -c 3 > /home/hh/Documents/Basecalled/20200820/uncalled_realtime.paf
```

I get the following error: 

```
Traceback (most recent call last):
  File "/home/hh/miniconda3/envs/UNCALLED/lib/python3.6/site-packages/uncalled-2.1-py3.6-linux-x86_64.egg/EGG-INFO/scripts/uncalled", line 308, in realtime_cmd
    if not client.run():
  File "/home/hh/miniconda3/envs/UNCALLED/lib/python3.6/site-packages/uncalled-2.1-py3.6-linux-x86_64.egg/uncalled/minknow_client.py", line 70, in run
    if not self._wait_for_start(steady_wait, refresh):
  File "/home/hh/miniconda3/envs/UNCALLED/lib/python3.6/site-packages/uncalled-2.1-py3.6-linux-x86_64.egg/uncalled/minknow_client.py", line 188, in _wait_for_start
    state = self._get_run_state()
  File "/home/hh/miniconda3/envs/UNCALLED/lib/python3.6/site-packages/uncalled-2.1-py3.6-linux-x86_64.egg/uncalled/minknow_client.py", line 170, in _get_run_state
    return self.connection.acquisition.get_acquisition_info().state
  File "/home/hh/miniconda3/envs/UNCALLED/lib/python3.6/site-packages/minknow_api-4.0.4-py3.6.egg/minknow_api/acquisition_service.py", line 231, in get_acquisition_info
    return run_with_retry(self._stub.get_acquisition_info, _message, _timeout, [], "minknow_api.acquisition.AcquisitionService")
  File "/home/hh/miniconda3/envs/UNCALLED/lib/python3.6/site-packages/minknow_api-4.0.4-py3.6.egg/minknow_api/acquisition_service.py", line 72, in run_with_retry
    result = MessageWrapper(method(message, timeout=timeout), unwraps=unwraps)
  File "/home/hh/miniconda3/envs/UNCALLED/lib/python3.6/site-packages/grpcio-1.32.0-py3.6-linux-x86_64.egg/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/hh/miniconda3/envs/UNCALLED/lib/python3.6/site-packages/grpcio-1.32.0-py3.6-linux-x86_64.egg/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "No acquisition run available"
	debug_error_string = "{"created":"@1601990520.207969892","description":"Error received from peer ipv4:127.0.0.1:8000","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"No acquisition run available","grpc_status":9}"
>
```

"No acquisition run available" does that mean I have an issue with MinKnow install/ have I missed something? 
Any advise or suggestions appreciated. 
Thank you in advance:-)  

Ubuntu 16.04
MinKnow 4.0.21

**Comment by skovaka** [comment]
I believe this sometimes happens when you try to run UNCALLED before you start the sequencing run. Try starting the sequencing run first, wait until the target temperature is reached, then run UNCALLED. As long you start before the first mux scan ends you will not miss any reads. Sorry about that, I know the README suggests you run UNCALLED before starting a run. I will try to a solution to this bug or else update the README, but that should work in the meantime.

**Comment by ChloeDG** [comment]
Ohhhhhhh, I see. Yup looks like it is working well after I start a run! Great, thank you!

**Comment by ChloeDG** [comment]
FYI working well for me! I see a nice enrichment when I exclude 'short' reads. 
:-)
