### ISSUE TITLE
Fast5 file `vbz` problem

### ISSUE THREAD

**Issue by peiyihe** [skovaka/UNCALLED#59]
Hi, Sam,

I'm trying to map a fast5 file with UNCALLED, it seems I need `vbz` for this file? Is there anything wrong? 
```
pyhe@PYHE_VM:~/UNCALLED/test_for_cam$ uncalled map index/example_ref fast5_filename.txt
Loading fast5s
Mapping
HDF5-DIAG: Error detected in HDF5 (1.8.21) thread 140581483063104:
  #000: H5Dio.c line 223 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 605 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 2093 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 3123 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1311 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 380 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 738 in H5PL__find(): can't open directory: /usr/local/hdf5/lib/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
Traceback (most recent call last):
  File "/home/pyhe/.local/bin/uncalled", line 341, in <module>
    map_cmd(conf, args)
  File "/home/pyhe/.local/bin/uncalled", line 157, in map_cmd
    for p in mapper.update():
RuntimeError: /read_0006a106-77eb-4752-b405-38d1635718fa/Raw/Signal: error in H5Dread
terminate called without an active exception
Aborted (core dumped)
pyhe@PYHE_VM:~/UNCALLED/test_for_cam$ pip install ont-vbz-hdf-plugin
```

**Comment by Happy0430room** [comment]
And also I'm trying UNCALLED, and I find when the input length is very small like 350bp, UNCALLED won't give the result? Will UNCALLED choose the length of input? For example, if the length is too short, we may regard this read as low quality read, and discard it directly?
![image](https://github.com/skovaka/UNCALLED/assets/52478488/1adb9c15-b3e7-4ec2-bbfb-fb2dd24121ea)

**Comment by skovaka** [comment]
VBZ is a compression plugin which sometimes must be manually installed: https://github.com/nanoporetech/vbz_compression
If you have any trouble see this previous issue for possible solutions: https://github.com/skovaka/UNCALLED/issues/38

**Comment by peiyihe** [comment]
Thanks! I am successful now.
