### ISSUE TITLE
Last channel is too large error

### ISSUE THREAD

**Issue by vineeth-s** [skovaka/UNCALLED#9]
Hi,

When I try to run UNCALLED for read_until whilst using a FLONGLE, I get the following error ... 

```
[14:59:17 - ReadUntil] Creating many chunk client with ReadCache data queue filtering to strand, strand2, and strand1 read chunks.
[14:59:17 - ReadUntil] Using pre-defined read classification map.
[14:59:17 - ReadUntil] Creating rpc connection on port 8008.
[14:59:17 - ReadUntil] Got rpc connection.
[14:59:17 - UNCALLED] Run already in progress
Traceback (most recent call last):
  File "./uncalled", line 287, in realtime_cmd
    cal = client.device.rpc.device.get_calibration(first_channel=1, last_channel=128)
...
File "/opt/ont/minknow/ont-python/lib/python2.7/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "last_channel is too large"
	debug_error_string = "{"created":"@1593781157.102897145","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"last_channel is too large","grpc_status":3}"
```

**Comment by vineeth-s** [comment]
I have changed the 512 which is for MinION to 126 for the Flongle and will see if this works

**Comment by vineeth-s** [comment]
The change in the last_channel parameter to 126 seems to have done the trick for the flongle, and it seems to be running

Thanks for making UNCALLED available
